#!/usr/bin/env python3.13
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

KEY_RE = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$")
MANAGEMENT_KEY_TODO = (
    "# TODO: Provision a dedicated XAI_MANAGEMENT_API_KEY; currently reusing "
    "XAI_API_KEY temporarily."
)


def _parse_value(raw: str) -> str:
    value = raw.strip()
    if not value:
        return ""

    if value[0] in ('"', "'"):
        quote = value[0]
        escaped = False
        chars: list[str] = []
        for ch in value[1:]:
            if escaped:
                chars.append(ch)
                escaped = False
                continue
            if ch == "\\":
                escaped = True
                continue
            if ch == quote:
                break
            chars.append(ch)
        return "".join(chars)

    return value.split("#", 1)[0].strip()


def _parse_env_file(path: Path) -> tuple[dict[str, str], list[str]]:
    values: dict[str, str] = {}
    order: list[str] = []
    if not path.exists():
        return values, order

    for line in path.read_text(encoding="utf-8").splitlines():
        match = KEY_RE.match(line)
        if not match:
            continue
        key = match.group(1)
        raw_value = match.group(2)
        if key not in order:
            order.append(key)
        values[key] = _parse_value(raw_value)

    return values, order


def _quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _resolve_value(
    key: str,
    *,
    force: bool,
    target_values: dict[str, str],
    source_values: dict[str, str],
    template_values: dict[str, str],
) -> tuple[str, str]:
    target_value = target_values.get(key, "")
    source_value = source_values.get(key, "")
    template_value = template_values.get(key, "")

    if not force and target_value.strip():
        return target_value, "target"

    if source_value.strip():
        return source_value, "source"

    return template_value, "template"


def _is_unset_or_placeholder(value: str) -> bool:
    normalized = value.strip()
    if not normalized:
        return True
    upper = normalized.upper()
    return upper.startswith("YOUR_")


def bootstrap_env(
    *,
    target_env: Path,
    template_env: Path,
    source_env: Path,
    force: bool,
) -> int:
    if not template_env.exists():
        print(f"Error: template env file not found: {template_env}", file=sys.stderr)
        return 1

    template_values, template_order = _parse_env_file(template_env)
    if not template_order:
        print(f"Error: no env keys found in template file: {template_env}", file=sys.stderr)
        return 1

    target_values, _ = _parse_env_file(target_env)

    source_values: dict[str, str]
    if source_env.exists():
        source_values, _ = _parse_env_file(source_env)
    else:
        source_values = {}
        print(
            f"Warning: source env file not found; using template/default values: {source_env}",
            file=sys.stderr,
        )

    resolved: dict[str, str] = {}
    origin: dict[str, str] = {}

    for key in template_order:
        value, value_origin = _resolve_value(
            key,
            force=force,
            target_values=target_values,
            source_values=source_values,
            template_values=template_values,
        )
        resolved[key] = value
        origin[key] = value_origin

    fallback_applied = False
    if "XAI_MANAGEMENT_API_KEY" in resolved:
        management_value = resolved["XAI_MANAGEMENT_API_KEY"]
        if _is_unset_or_placeholder(management_value):
            resolved["XAI_MANAGEMENT_API_KEY"] = resolved.get("XAI_API_KEY", "")
            origin["XAI_MANAGEMENT_API_KEY"] = "fallback_from_XAI_API_KEY"
            fallback_applied = True

    lines = [
        "# Environment variables for Wet Donkey (auto-generated by bootstrap_env_from_fh.py)",
        "# Do not commit secrets.",
        "",
    ]

    for key in template_order:
        if key == "XAI_MANAGEMENT_API_KEY":
            lines.append(MANAGEMENT_KEY_TODO)
        lines.append(f"{key}={_quote_env_value(resolved.get(key, ''))}")

    target_env.parent.mkdir(parents=True, exist_ok=True)
    target_env.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(target_env, 0o600)

    source_reused = sorted(key for key, value_origin in origin.items() if value_origin == "source")
    payload = {
        "status": "ok",
        "target_env": str(target_env),
        "template_env": str(template_env),
        "source_env": str(source_env),
        "keys_written": len(template_order),
        "source_reused_keys": source_reused,
        "management_key_fallback_applied": fallback_applied,
        "management_key_todo_comment_added": True,
    }
    print(json.dumps(payload))
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create/refresh Wet Donkey .env by reusing compatible keys from Flaming Horse .env."
    )
    parser.add_argument(
        "--target-env",
        default="/Users/velocityworks/IdeaProjects/wet-donkey/.env",
        help="Target .env path to create/update",
    )
    parser.add_argument(
        "--template-env",
        default="/Users/velocityworks/IdeaProjects/wet-donkey/.env.example",
        help="Wet Donkey .env template path",
    )
    parser.add_argument(
        "--source-env",
        default="/Users/velocityworks/IdeaProjects/flaming-horse/.env",
        help="Source Flaming Horse .env path",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Ignore existing target values and prefer source/template values",
    )

    args = parser.parse_args()

    rc = bootstrap_env(
        target_env=Path(args.target_env),
        template_env=Path(args.template_env),
        source_env=Path(args.source_env),
        force=args.force,
    )
    sys.exit(rc)


if __name__ == "__main__":
    main()
