# scripts/scaffold_scene.py
import argparse
from pathlib import Path

def scaffold_scene(project_dir: str, scene_number: int, scene_title: str):
    """
    Generates a new Manim scene file from a template.
    """
    project_dir = Path(project_dir)
    scenes_dir = project_dir / "scenes"
    scenes_dir.mkdir(exist_ok=True)
    
    # Format scene number to be two digits (e.g., 1 -> 01)
    scene_num_str = f"{scene_number:02d}"
    
    # Sanitize title for file name
    safe_title = "".join(c if c.isalnum() else "_" for c in scene_title.lower().replace(" ", "_"))
    
    file_name = f"scene_{scene_num_str}_{safe_title}.py"
    file_path = scenes_dir / file_name

    if file_path.exists():
        print(f"Error: Scene file already exists at {file_path}")
        return

    # The content that will be written to the new scene file
    template = f"""from manim import *
from wet_donkey.scene_helpers import *

# Narration script for this scene (will be populated by the narration phase)
SCRIPT = {{
    "scene_{scene_num_str}": "..."
}}

class {safe_title.capitalize()}(Scene):
    def construct(self):
        # This context manager will time the voiceover and scene animations
        with self.voiceover(text=SCRIPT["scene_{scene_num_str}"]) as tracker:
            # SLOT_START:scene_body
            # The code generated by the LLM will be injected here.
            # Example:
            # title = Text("My Awesome Scene")
            # self.play(Write(title), run_time=tracker.duration_for_words(3))
            # SLOT_END:scene_body
            pass
"""
    
    with open(file_path, "w") as f:
        f.write(template)
        
    print(f"Scaffolded new scene: {file_path}")

def main():
    parser = argparse.ArgumentParser(description="Scaffold a new Manim scene file.")
    parser.add_argument("--project-dir", required=True, help="The project directory.")
    parser.add_argument("--scene-number", required=True, type=int, help="The numerical index of the scene (e.g., 1, 2).")
    parser.add_argument("--scene-title", required=True, help="The title of the scene.")

    args = parser.parse_args()
    
    scaffold_scene(args.project_dir, args.scene_number, args.scene_title)

if __name__ == "__main__":
    main()
